spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:sales
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
springdoc.swagger-ui.path: /api-docs
jwt:
  secret: CHANGE_ME
  expiration: 21600000
